version: 2.1
orbs:
  docker: circleci/docker@2.0.1

jobs:

  deploy:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: suculent/arduino-docker-build
          tag: latest
      - docker/push:
          digest-path: /tmp/digest.txt
          image: suculent/arduino-docker-build
          tag: latest
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
            docker tag $(</tmp/digest.txt) suculent/arduino-docker-build:latest

  test:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: suculent/arduino-docker-build
          tag: future

#
# WORKFLOWS
#

workflows:
  version: 2
  build:
    jobs:
      - test:
          context:
            - dockerhub
      - deploy:
          context:
            - dockerhub
          requires: 
              - test
          filters:
            branches:
              only: master